In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()

Saving spam.csv to spam.csv


In [5]:
df = pd.read_csv('spam.csv')
df

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [6]:
df.Category.value_counts()

,count
Category,
ham,4825
spam,747


In [7]:
df.shape

(5572, 2)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Category, test_size=0.2,random_state=1)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()


In [10]:
emails = [
            'Upto 20% discount reward!',
            'Hey mohan, discount Upto'
         ]

emails_cv = v.fit_transform(emails)
emails_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 6)>

In [11]:
emails_cv.toarray()

array([[1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 1]])

In [12]:
v.get_feature_names_out()

array(['20', 'discount', 'hey', 'mohan', 'reward', 'upto'], dtype=object)

In [13]:
pd.DataFrame(emails_cv.toarray(), columns=v.get_feature_names_out())

,20,discount,hey,mohan,reward,upto
0,1,1,0,0,1,1
1,0,1,1,1,0,1


In [17]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58978 stored elements and shape (4457, 7711)>

In [18]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
X_train_cv.shape

(4457, 7711)

In [20]:
X_train_cv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [21]:
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'zyada', 'èn', '〨ud'],
      dtype=object)

In [22]:
pd.DataFrame(X_train_cv.toarray(), columns=v.get_feature_names_out())

,00,000,008704050406,0121,01223585236,01223585334,0125698789,02,0207,02072069400,...,zed,zeros,zhong,zindgi,zoe,zoom,zouk,zyada,èn,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [23]:
v.vocabulary_

{'hi': 3423,
 'where': 7442,
 'are': 1051,
 'you': 7674,
 'we': 7370,
 're': 5564,
 'at': 1119,
 'and': 963,
 'they': 6794,
 'not': 4813,
 'keen': 3906,
 'to': 6889,
 'go': 3153,
 'out': 4985,
 'kind': 3940,
 'of': 4872,
 'am': 937,
 'but': 1578,
 'feel': 2795,
 'shouldn': 6077,
 'so': 6230,
 'can': 1632,
 'tomo': 6910,
 'don': 2408,
 'mind': 4474,
 'do': 2377,
 'if': 3593,
 'home': 3469,
 'then': 6782,
 'come': 1908,
 'down': 2433,
 'within': 7511,
 'min': 4471,
 'when': 7438,
 'guys': 3278,
 'getting': 3116,
 'back': 1196,
 'said': 5845,
 'were': 7419,
 'thinking': 6804,
 'about': 759,
 'staying': 6408,
 'for': 2927,
 'mcr': 4392,
 'tell': 6710,
 'my': 4650,
 'bad': 1199,
 'character': 1738,
 'which': 7448,
 'dnt': 2376,
 'lik': 4108,
 'in': 3633,
 'me': 4393,
 'll': 4156,
 'try': 7007,
 'change': 1730,
 'lt': 4243,
 'gt': 3254,
 'add': 813,
 'tat': 6671,
 'new': 4743,
 'year': 7650,
 'resolution': 5708,
 'waiting': 7308,
 'ur': 7147,
 'reply': 5688,
 'be': 1270,
 'frank': 2963,
 'go

In [24]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [25]:
X_test_cv = v.transform(X_test)

In [26]:
X_test_cv.toarray().shape

(1115, 7711)

In [27]:
model.score(X_test_cv, y_test)

0.989237668161435

In [28]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       968
        spam       0.98      0.94      0.96       147

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [29]:
emails = [
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Hey mohan, can we get together to watch footbal game tomorrow?'
]

In [30]:
emails_count = v.transform(emails)
emails_count.toarray().shape

(2, 7711)

In [31]:
model.predict(emails_count)

array(['spam', 'ham'], dtype='<U4')